version: "3.3"

services:
  db-postgres:
    image: "postgres"
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
