version: "3.3"

services:
  db-postgres:
    image: "postgres"
    restart: always
    container_name: masterclass_db
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - docker_data:/data/postgres
    networks:
      compose-networks:
        ipv4_address: 172.28.1.3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  db-pgadmin:
    image: "dpage/pgadmin4"
    restart: always
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@email.com"
      PGADMIN_DEFAULT_PASSWORD: "user"
    ports:
      - "5433:80"
    volumes:
      - docker_data:/data/pgadmin
    depends_on:
      - db-postgres
    networks:
      compose-networks:
        ipv4_address: 172.28.1.4
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
networks:
  compose-networks:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  docker_data:
    driver: local
